# 04 Data Preprocessing dengan Scikit-Learn

Topik pembelajaran kita kali ini adalah terkait data processing dengan menggunakan Scikit-Learn. 

## Sample Data

Pada sesi pembelajaran sebelumnya, saya pernah menyampaikan bahwa fase mempersiapkan dataset bisa jadi tahapan yang paling banyak membutuhkan waktu dan effort dalam suatu proyek Data Science maupun Machine Learning. Dalam sesi pembelajaran kali ini, kita berkenalan dengan beberapa teknik data preprocessing. 

Modul Scikit-Learn juga menyertakan sejumlah teknik data pre-processing yang umum ditemui. Nah disini kita akan mempelajari beberapa diantaranya. 

Kita akan persiapkan terlebih dahulu sample dataset yang akan kita olah. Nah disini pertama-tama kita akan import `numpy` sebagai `np` terlebih dahulu karena datasetnya akan kita generate sebagai `numpy array`. 

In [1]:
import numpy as np

Lalu terkait dengan modul pre-processing, modul pre-processing ini bisa kita import dengan memanggil 

In [2]:
from sklearn import preprocessing

Nah itu tadi 2 modul yang harus kita import. Lalu berikutnya kita bisa persiapkan dataset dummy dalam bentuk numpy array untuk keperluan belajar kita kali ini :

In [3]:
sample_data = np.array([
    [2.1, -1.9, 5.5],
    [-1.5, 2.4, 3.5],
    [0.5, -7.9, 5.6],
    [5.9, 2.3, -5.8]
])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Nah kalau kita preview kembali materi yang disampaikan pada sesi pembelajaran sebelumnya, maka dataset ini bisa kita pandang sebagai dataset features. Dan kalau kita lihat disini, jumlah instance yang ada 4 instance atau 4 baris. 

Lalu terkait dengan jumlah features, dataset ini terbagi dalam 3 features. 

features pertama :
```python
sample_data = np.array([
    [2.1, ..., ...],
    [-1.5, ..., ...],
    [0.5, ..., ...],
    [5.9, ..., ...]
])
```

lalu features kedua :
```python
sample_data = np.array([
    [..., -1.9, ...],
    [..., 2.4, ...],
    [..., -7.9, ...],
    [..., 2.3, ...]
])
```

dan features ketiga :
```python
sample_data = np.array([
    [..., ..., 5.5],
    [..., ..., 3.5],
    [..., ..., 5.6],
    [..., ..., -5.8]
])
```

yang ketiga features (kolom) dan 4 instance (baris) tadi kita tampung dalam variable `sample_data`

Nah untuk lebih jelasnya lagi kita juga bisa menampilkan dimensi dari dataset ini dengan memanggil 

In [4]:
sample_data.shape

(4, 3)

itu dia hasilnya $(4, 3)$ atau dengan kata lain instance-nya ada 4 dan features-nya ada 3. 

---

## Binarisation 

Teknik data pre-processing pertama yang akan kita pelajari disini adalah **Binarisation**. Tujuan utama dari teknik ini adalah untuk menghasilkan suatu data yang terdiri dari 2 nilai numerik saja, yaitu : 0 dan 1. 

Disini kita coba dulu tampilkan terlebih dahulu dataset yang telah kita bentuk sebelumnya. 

In [5]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Nah itu merupakan dataset yang kita bentuk sebelumnya. Nah bisa nampak diatas, dataset-nya terdiri dari sekumpulan nilai floatin point (angka koma) yang cukup beragam. 

Semisal saja disini kita dihadapkan pada kebutuhan untuk mengkonversi setiap nilai numerik yang lebih besar dari $0.5$ atau $> 0.5$ menjadi 1

dan sisanya kita konversikan menjadi $0$  $(< 0.5$ menjadi $0)$

Kebutuhan semacam ini bisa kita penuhi dengan memanfaatkan **class Binarizer**

Kita akan demokan caranya :

1. Pertama-tama kita akan bentuk dulu objek binarizer-nya. Caranya cukup mudah kita tinggal panggil saja 

In [6]:
preprocessor = preprocessing.Binarizer(threshold=0.5)

parameter yang bisa kita tambahkan dalam Binarizer adalah threshold yang kita set $0.5$. Nah pemanggilan semacam diatas akan menghasilkan sebuah objek Binarizer yang kita tampung dalam variable `preprocessor`

Nah pada tahapan selanjutnya kita akan menggunakan proses transformasi terhadap sample data yang kita miliki tadi. Caranya cukup mudah, kita panggil saja :

In [7]:
binarized_data = preprocessor.transform(sample_data)
binarized_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

Itu dia hasilnya ya diatas hasil dari proses binarisation ini adalah suatu dataset yang **hanya terdiri dari dua nilai yaitu 1 dan 0**. Dimana batasnya tadi sudah kita tentukan dari nilai `(threshold=0.5)`. Artinya setiap nilai yang lebih kecil atau sama dengan 0.5 akan dikonversikan menjadi nilai 0. 

Sebagai contoh disini nilai yang kurang dari 0.5 atau sama dengan 0.5 $(\geq 0.5)$:

```python
array([[ ..., -1.9,  ...],
       [-1.5,  ...,  ...],
       [ 0.5, -7.9,  ...],
       [ ...,  ..., -5.8]])
```

akan diubah menjadi 0 ketika binarized data :

```python
array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])
```

Sedangkan untuk nilai-nilai yang lebih dari 0.5 $(> 0.5)$:
```python
array([[ 2.1, ...,  5.5],
       [ ..., 2.4,  3.5],
       [ ..., ...,  5.6],
       [ 5.9, 2.3, ...]])
```

akan diubah menjadi 1 ketika binarized data :
```python
array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])
```

Nah sekali lagi mohon diperhatikan, untuk **nilai yang sama dengan nilai threshold-nya, maka dia akan diubah menjadi nilai 0**.

Atau kalau mau kita sederhanakan, **nilai 1 akan kita peroleh dari suatu nilai yang lebih besar dari nilai Threshold-nya**, baru sisanya akan dikonversikan menjadi nilai 0. 

Harapannya bisa dipahami ya? Kasus yang saya hadirkan disini merupakan bentuk paling sederhana dari teknik binarisation pada data pre-processing. Dalam beberapa sesi pembelajaran selanjutnya, kita akan bertemu dengan bentuk binarisation lainnya. 

---

---

## Scaling 

Teknik data pre-processing kedua yang akan kita pelajari disini adalah **scalling**. Sesuai dengan namanya, tujuan utama dari scalling ini untuk menghasilkan suatu data numerik yang berada dalam rentang skala tertentu. Nah disini saya coba tampilkan kembali dataset yang sudah kita bentuk sebelumnya. Oleh karenanya disini kita coba tampilkan isi dari variable `sample_data`. Karena variable `sample_data` ini yang kita gunakan untuk menampung dataset yang kita bentuk sebelumnya. 

In [8]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Bisa dilihat data yang kita buat tadi memiliki rentang nilai mulai dari $-7.9$ sebagai nilai terkecil sampai dengan nilai $5.9$ sebagai nilai terbesarnya. Semisal kali ini kita dihadapkan pada kebutuhan untuk mengkonversi sekumpulan nilai floating point ini kedalam rentang nilai mulai dari 0 sampai dengan 1. Kebutuhan semacam ini bisa kita penuhi dengan memanfaatkan **`class scaler`**. 

Pada dasarnya teknik scalling ada berbagai macam, disini kita akan gunakan scalling yang paling sederhana, yaitu `MinMaxScaler`. 

Nah caranya juga cukup mudah kita tinggal panggil `preprocessing.MinMaxScaller` lalu kita sertakan parameter penting yaitu `feature_range`. Nah parameter `feature_range` ini akan membutuhkan data bertipe tuple yang akan memuat 2 nilai. Nah untuk kasus kita kali ini, nilainya kita set sebagai 0 dan 1. 

0 disini akan mengindikasikan nilai terkecil dari skala yang baru dan nilai 1 akan mengidikasikan nilai terbesar dari skala yang baru nanti. Nah kita tampung dalam sebuah variable bernama `processor`

In [9]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))

Nah selanjutnya objek scaler ini akan kita fit terhadap sample data yang kita miliki. Caranya kita ketik kembali variable `preprocessor` tadi lalu kita `fit`-kan dengan parameter `sample_data` yang kita buat tadi

In [10]:
preprocessor.fit(sample_data)

MinMaxScaler()

Nah setelah kita fit terhadap `sample_data` kita, maka scaler ini bisa kita gunakan untuk melakukan proses transformasi data. Untuk kasus kita kali ini, transformasi datanya juga akan kita kenakan pada `sample_data` yang kita miliki tadi. Oleh karenanya kita panggil `preprosessor.transform` lalu kita masukan `sample_data`-nya. Nah hasil dari tranformasi data ini akan kita tampung dalam variable `scaled_data`

In [11]:
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Dan itu dia hasilnya diatas. Bisa dilihat nilai terkecilnya adalah 0 dan nilai terbesarnya adalah 1. Dan nilai ini merupakan hasil transformasi dari `sample_data` yang kita buat tadi :

```python
array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])
```

Jadi kalau kita mau simpulkan disini, proses MinMaxScaler ini digunakan untuk mengubah skala nilai terkecil dan nilai terbesar dari dataset yang kita miliki ke skala tertentu (range). Untuk kasus kita kali ini, skalanya adalah nilai yang terkecilnya adalah 0 dan nilai yang terbesarnya adalah 1. Dan ini adalah hasil dari transformasinya :

```python
array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])
```

Oh ya kalo proses fitting dan transformasinya tadi dikenakan pada data yang sama, yaitu `sample_data`. Nah dalam Scikit-Learn proses ini bisa kita satukan dengan memanfaatkan proses `fit_transform`. 

Nah caranya cukup sederhana, kita panggil saja objek `preprocessor`-nya atau objek scaler-nya. Lalu kita panggil `fit_transform` lalu kita sertakan `sample_data` sebagai parameternya. 

```python
preprocessor.fit_transform(sample_data)
```

Cara ini berati proses `fit` dan proses `transform` dikenakan pada data yang sama. Dan selanjutnya, hasil dari proses transformasinya kita akan tampung dalam variable `scaled_data`

In [12]:
scaled_data = preprocessor.fit_transform(sample_data)

kita tampilkan nilai dari `scaled_data`

In [13]:
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Nah itu dia hasilnya. kalau kita perhatikan bersama, proses diatas dengan proses sebelumnya menghasilkan nilai yang sama. Bedanya kalau di cara yang pertama proses fitting dan transform-nya terpisah atau dikerjakan dengan menggunakan dua metode yang berbeda. 

Sedangkan cara yang terakhir, proses fitting dan transformasi datanya dilakukan dengan menggunakan satu kali pemanggilan method, yaitu method `fit_transform`

---

---

## L1 Normalisation : Least Absolute Deviations

### Referensi : https://en.wikipedia.org/wiki/Least_absolute_deviations

Teknik data pre-processing ketiga dan keempat yang akan kita pelajari disini adalah **normalisation**. Sesuai dengan namanya, tujuan utama dari teknik ini adalah untuk melakukan normalisasi terhadap data numerik yang kita miliki. 

Kita coba tampilkan lagi ya dataset yang kita bentuk sebelumnya :

In [14]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Nah pada kasus normalisation pertama ini, kita akan menerapkan **Least Absolut Deviations**. Bagi kalian yang tertarik untuk mempelajari lebih lanjut mengenai Least Absolut Deviations, sudah kami sediakan refrensi sederhana. 

Referensi : https://en.wikipedia.org/wiki/Least_absolute_deviations

Selanjutnya saya akan coba demo-kan proses untuk menerapkan teknik normalisation ini. 

In [15]:
l1_normalisation_data = preprocessing.normalize(sample_data, norm='l1')

- Disini pertama-tama kita panggil `preprocessing` lalu diikuti dengan `.normalize`.
- Nah `.normalize` ini akan membutuhkan dua parameter :
    - parameter pertama adalah datanya, atau `sample_data`-nya.
    - lalu parameter keduanya adalah parameter `norm=`,
        - nah untuk kasus kita kali ini parameter `norm`-nya kita beri nilai string `l1`
        - nah normalisasi L1 ini akan berasosiasi dengan normalisasi yang menerapkan Least Absolut Deviations
- Pemanggilan fungsi `preprocessing.normalise` ini akan menghasilkan data yang ternormalisasi.
- Lalu kita simpan dalam variable `l1_normalisation_data`

In [16]:
l1_normalisation_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

Nah untuk kasus kita disini, data yang sudah dinormalisasi akan ditampung dalam variable `l1_normalisation_data`. 

Dan hasil diatas adalah hasil dari normalisasi dari `sample_data`

Kita coba lanjut ya ke normalisasi yang kedua, yaitu normalisasi L2.

---

---

## Normalisation : Least Squares

Untuk kasus normalisasi yang kedua, kita akan menerapkan **Least Squares**. Bagi kalian yang ingin mempelajari lebih lanjut mengenai Least Squares, saya juga menyertakan refrensi sederhana sebagai berikut :

Refrensi : https://en.wikipedia.org/wiki/Least_squares

Pertama kita tampilkan dulu ya `sample_data`-nya.

In [17]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Ini merupakan `sample_data` sebelum kita mengenakan proses normalisasi L2. Lalu berikutnya akan saya demokan proses untuk menerapkan teknik normalisasi kedua ini. 

Nah disini juga caranya cukup sederhana ya :

In [18]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')

kita panggil saja `preprocessing.normalize` lalu kita menyertakan 2 parameter : 
- Parameter pertama adalah `sample_data`-nya,
- dan parameter kedua adalah parameter `norm`. Kali ini parameter `norm`-nya kita beri nilai `L2`. 

Nah normalisasi `L2` ini berasosiasi dengan teknik yang namanya **Least Squares**. Lalu berikutnya pemanggilan `preprocessing.normalize` ini akan menghasilkan data yang sudah ternormalisasi. 

Data tersebut kita tampung ke dalam variable `l2_normalised_data`. Untuk selanjutnya kita tampilkan :

In [19]:
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])

Nah itu dia hasilnya. Hasil diatas adalah hasil `sample_data` setelah normalisasi L2. Atau proses normalisasi dengan menerapkan Least Squares. 

---

Bagaimana? semoga dapat dipahami ya?

Kedua kasus yang saya hadirkan disini merupakan bentuk sederhana dari teknik normalisasi pada data preprocessing. Dalam beberapa sesi selanjutnya kita akan bertemu dengan bentuk normalisasi lainnya. Nah demikian sesi pembelajaran terkait Data Pre-Processing dengan Scikit-Learn. 