# 04 Data Preprocessing dengan Scikit-Learn

Topik pembelajaran kita kali ini adalah terkait data processing dengan menggunakan Scikit-Learn. 

## Sample Data

Pada sesi pembelajaran sebelumnya, saya pernah menyampaikan bahwa fase mempersiapkan dataset bisa jadi tahapan yang paling banyak membutuhkan waktu dan effort dalam suatu proyek Data Science maupun Machine Learning. Dalam sesi pembelajaran kali ini, kita berkenalan dengan beberapa teknik data preprocessing. 

Modul Scikit-Learn juga menyertakan sejumlah teknik data pre-processing yang umum ditemui. Nah disini kita akan mempelajari beberapa diantaranya. 

Kita akan persiapkan terlebih dahulu sample dataset yang akan kita olah. Nah disini pertama-tama kita akan import `numpy` sebagai `np` terlebih dahulu karena datasetnya akan kita generate sebagai `numpy array`. 

In [1]:
import numpy as np

Lalu terkait dengan modul pre-processing, modul pre-processing ini bisa kita import dengan memanggil 

In [2]:
from sklearn import preprocessing

Nah itu tadi 2 modul yang harus kita import. Lalu berikutnya kita bisa persiapkan dataset dummy dalam bentuk numpy array untuk keperluan belajar kita kali ini :

In [3]:
sample_data = np.array([
    [2.1, -1.9, 5.5],
    [-1.5, 2.4, 3.5],
    [0.5, -7.9, 5.6],
    [5.9, 2.3, -5.8]
])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Nah kalau kita preview kembali materi yang disampaikan pada sesi pembelajaran sebelumnya, maka dataset ini bisa kita pandang sebagai dataset features. Dan kalau kita lihat disini, jumlah instance yang ada 4 instance atau 4 baris. 

Lalu terkait dengan jumlah features, dataset ini terbagi dalam 3 features. 

features pertama :
```python
sample_data = np.array([
    [2.1, ..., ...],
    [-1.5, ..., ...],
    [0.5, ..., ...],
    [5.9, ..., ...]
])
```

lalu features kedua :
```python
sample_data = np.array([
    [..., -1.9, ...],
    [..., 2.4, ...],
    [..., -7.9, ...],
    [..., 2.3, ...]
])
```

dan features ketiga :
```python
sample_data = np.array([
    [..., ..., 5.5],
    [..., ..., 3.5],
    [..., ..., 5.6],
    [..., ..., -5.8]
])
```

yang ketiga features (kolom) dan 4 instance (baris) tadi kita tampung dalam variable `sample_data`

Nah untuk lebih jelasnya lagi kita juga bisa menampilkan dimensi dari dataset ini dengan memanggil 

In [4]:
sample_data.shape

(4, 3)

itu dia hasilnya $(4, 3)$ atau dengan kata lain instance-nya ada 4 dan features-nya ada 3. 

---

## Binarisation 

Teknik data pre-processing pertama yang akan kita pelajari disini adalah **Binarisation**. Tujuan utama dari teknik ini adalah untuk menghasilkan suatu data yang terdiri dari 2 nilai numerik saja, yaitu : 0 dan 1. 

Disini kita coba dulu tampilkan terlebih dahulu dataset yang telah kita bentuk sebelumnya. 

In [5]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Nah itu merupakan dataset yang kita bentuk sebelumnya. Nah bisa nampak diatas, dataset-nya terdiri dari sekumpulan nilai floatin point (angka koma) yang cukup beragam. 

Semisal saja disini kita dihadapkan pada kebutuhan untuk mengkonversi setiap nilai numerik yang lebih besar dari $0.5$ atau $> 0.5$ menjadi 1

dan sisanya kita konversikan menjadi $0$  $(< 0.5$ menjadi $0)$

Kebutuhan semacam ini bisa kita penuhi dengan memanfaatkan **class Binarizer**

Kita akan demokan caranya :

1. Pertama-tama kita akan bentuk dulu objek binarizer-nya. Caranya cukup mudah kita tinggal panggil saja 

In [6]:
preprocessor = preprocessing.Binarizer(threshold=0.5)

parameter yang bisa kita tambahkan dalam Binarizer adalah threshold yang kita set $0.5$. Nah pemanggilan semacam diatas akan menghasilkan sebuah objek Binarizer yang kita tampung dalam variable `preprocessor`

Nah pada tahapan selanjutnya kita akan menggunakan proses transformasi terhadap sample data yang kita miliki tadi. Caranya cukup mudah, kita panggil saja :

In [7]:
binarized_data = preprocessor.transform(sample_data)
binarized_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

Itu dia hasilnya ya diatas hasil dari proses binarisation ini adalah suatu dataset yang **hanya terdiri dari dua nilai yaitu 1 dan 0**. Dimana batasnya tadi sudah kita tentukan dari nilai `(threshold=0.5)`. Artinya setiap nilai yang lebih kecil atau sama dengan 0.5 akan dikonversikan menjadi nilai 0. 

Sebagai contoh disini nilai yang kurang dari 0.5 atau sama dengan 0.5 $(\geq 0.5)$:

```python
array([[ ..., -1.9,  ...],
       [-1.5,  ...,  ...],
       [ 0.5, -7.9,  ...],
       [ ...,  ..., -5.8]])
```

akan diubah menjadi 0 ketika binarized data :

```python
array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])
```

Sedangkan untuk nilai-nilai yang lebih dari 0.5 $(> 0.5)$:
```python
array([[ 2.1, ...,  5.5],
       [ ..., 2.4,  3.5],
       [ ..., ...,  5.6],
       [ 5.9, 2.3, ...]])
```

akan diubah menjadi 1 ketika binarized data :
```python
array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])
```

Nah sekali lagi mohon diperhatikan, untuk **nilai yang sama dengan nilai threshold-nya, maka dia akan diubah menjadi nilai 0**.

Atau kalau mau kita sederhanakan, **nilai 1 akan kita peroleh dari suatu nilai yang lebih besar dari nilai Threshold-nya**, baru sisanya akan dikonversikan menjadi nilai 0. 

Harapannya bisa dipahami ya? Kasus yang saya hadirkan disini merupakan bentuk paling sederhana dari teknik binarisation pada data pre-processing. Dalam beberapa sesi pembelajaran selanjutnya, kita akan bertemu dengan bentuk binarisation lainnya. 

---

---